### ISSUE TITLE
Hotkey without window

### ISSUE THREAD

**Issue by KoB-Kirito** [mrousavy/Hotkeys#2]
My application has no window, do you support that?

**Comment by mrousavy** [comment]
Due to the Windows API structure, it is not possible to use Hotkeys without a window (for reference purposes).

You can achieve this by creating a 0x0 window yourself, which is invisible for the user in every aspect (not on screen, not in task bar, not in tab switcher, not in task manager at the top, etc), you just need the IntPtr handle to that window for the Hotkeys API.

**Comment by KoB-Kirito** [comment]
Meh. Okay, thx.

**Comment by mrousavy** [comment]
Closing this. If you're having trouble setting this up, feel free to re-open this issue and I can help you.
